version: "3.9"
services:
  db:
    image: "postgres:16.0"
    container_name: "slack_messenger_postgres_dev"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slack_messenger_dev
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
  web:
    container_name: "slack_messenger_web_dev"
    env_file:
      - ./.env
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: slack_messenger_dev
    build:
      dockerfile: local.dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - "db"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: sh -c "/bin/bash"
